apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.chaos-mesh.org
    chart: chaos-mesh
    targetRevision: "*"
    helm:
      releaseName: chaos-mesh
      values: |
        imagePullSecrets:
          - name: ghcr-pull-secret
        controllerManager:
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
        chaosDaemon:
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
        dashboard:
          securityMode: false
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            hosts:
              - name: chaos-mesh.natejsimonsen.com
                tls: true
                tlsSecret: chaos-mesh-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
