apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: "*"
    helm:
      releaseName: keda
      values: |
        imagePullSecrets:
          - name: ghcr-pull-secret
        resources:
          operator:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
          metricServer:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
          webhooks:
            requests:
              memory: 32Mi
            limits:
              memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
