apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*"
    helm:
      releaseName: kps
      values: |
        global:
          imagePullSecrets:
            - name: ghcr-pull-secret
        grafana:
          adminPassword: "admin"
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            hosts:
              - grafana.natejsimonsen.com
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.natejsimonsen.com
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            hosts:
              - prometheus.natejsimonsen.com
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.natejsimonsen.com
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 1Gi
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                memory: 64Mi
              limits:
                memory: 128Mi
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            hosts:
              - alertmanager.natejsimonsen.com
            tls:
              - secretName: alertmanager-tls
                hosts:
                  - alertmanager.natejsimonsen.com
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
