apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.min.io
    chart: minio
    targetRevision: "*"
    helm:
      releaseName: minio
      values: |
        mode: standalone
        rootUser: admin
        rootPassword: changeme123
        persistence:
          size: 20Gi
        consoleService:
          type: ClusterIP
        resources:
          requests:
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
