apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.min.io
    chart: minio
    targetRevision: "*"
    helm:
      releaseName: minio
      values: |
        imagePullSecrets:
          - name: ghcr-pull-secret
        mode: standalone
        rootUser: admin
        rootPassword: changeme123
        persistence:
          size: 20Gi
        consoleService:
          type: ClusterIP
        consoleIngress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - minio.natejsimonsen.com
          tls:
            - secretName: minio-tls
              hosts:
                - minio.natejsimonsen.com
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
