apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: "*"
    helm:
      releaseName: tempo
      values: |
        global:
          imagePullSecrets:
            - name: ghcr-pull-secret
        tempo:
          reportingEnabled: false
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
