{{- if .Values.grafanaCloud.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GRAFANA_CLOUD_API_KEY: {{ .Values.grafanaCloud.apiKey | quote }}
  GRAFANA_CLOUD_PROMETHEUS_URL: {{ .Values.grafanaCloud.prometheus.url | quote }}
  GRAFANA_CLOUD_METRICS_USER: {{ .Values.grafanaCloud.prometheus.username | quote }}
  GRAFANA_CLOUD_LOKI_URL: {{ .Values.grafanaCloud.loki.url | quote }}
  GRAFANA_CLOUD_LOGS_USER: {{ .Values.grafanaCloud.loki.username | quote }}
  GRAFANA_CLOUD_TEMPO_ENDPOINT: {{ .Values.grafanaCloud.tempo.endpoint | quote }}
  GRAFANA_CLOUD_TEMPO_USER: {{ .Values.grafanaCloud.tempo.username | quote }}
  GRAFANA_CLOUD_PROFILES_URL: {{ .Values.grafanaCloud.profiles.url | quote }}
  GRAFANA_CLOUD_PROFILES_USER: {{ .Values.grafanaCloud.profiles.username | quote }}
{{- end }}
